# Generated by Django 3.2.15 on 2023-06-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eno', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=40)),
                ('esal', models.IntegerField()),
                ('eaddr', models.CharField(max_length=60)),
            ],
        ),
    ]
